'use strict';
window.HeartsText = (() => {
  const en = {
    title:'Hearts',you:'You',menu:'Menu',help:'How to play',close:'Close',back:'Back to the game',settings:'Settings',newGame:'New game',restartTitle:'Start a new game?',restartText:'Your current game will be replaced.',keepPlaying:'Keep playing',start:'Start a new game',
    totalScores:'Total scores · lowest wins',handPoints:'This hand: you have {n} points.',lastTrick:'Last trick',saveNote:'Your progress is saved automatically.',savedProblem:'Progress could not be saved. Keep this tab open.',recovered:'Your game was recovered from the previous save.',damaged:'The saved game could not be restored. A new game is ready.',
    choose3:'Choose 3 cards',ready:'Ready to pass',passLeft:'Pass left',passRight:'Pass right',passAcross:'Pass across',passTo:'Pass {direction} to {name}',left:'left',right:'right',across:'across',hold:'No passing this hand',count3:'{n} of 3',limit3:'Three cards chosen. Put one back before choosing another.',received:'Your new cards',receivedFrom:'3 cards received from {name}',newLabel:'NEW',continue:'Continue',begin:'Start playing',yourTurn:'Your turn',turn:'{name}’s turn',chooseCard:'Choose a card',chooseSuit:'Choose {suit}',leadTwo:'Play the 2 of clubs',follow:'Your turn · follow {suit}',playCard:'Play card',choose1:'Choose 1',wait:'Please wait',nextTrick:'Next trick',seeScores:'See scores',cardPlayed:'Trick complete',trickWon:'{name} took the trick · {n} points',yourTrick:'You took the trick · {n} points',chooseLegal:'Choose a highlighted card that follows the rules.',selected:'{card} selected. Press Play card to confirm.',
    clubs:'clubs',diamonds:'diamonds',spades:'spades',hearts:'hearts',ace:'Ace',jack:'Jack',queen:'Queen',king:'King',cardName:'{rank} of {suit}',handNumber:'Hand {n}',points:'{n} points',player:'Player',thisHand:'This hand',total:'Total',handComplete:'Hand complete',lowest:'Lowest total wins.',youWon:'You won!',won:'{name} won',lowestScore:'{n} points · lowest total',moon:'{name} shot the moon',moonDetail:'All 13 hearts and the queen of spades went to one player. Everyone else adds 26 points.',endReason:'A player reached 100 points. The lowest total wins.',tie:'Lowest scores tied. Play another hand.',nextPass:'Next hand: pass {direction}.',nextHold:'Next hand: keep your cards.',playAgain:'Play again',reviewTrick:'Review last trick',tookTrick:'{name} took this trick.',youTookTrick:'You took this trick.',led:'{name} led {suit}.',noPoints:'No hearts or queen of spades.',queenPoints:'Queen of spades: 13',heartPoints:'Hearts: {n}',
    language:'Language',pace:'Computer speed',slow:'Gentle',normal:'Normal',fast:'Quick',sound:'Soft card sounds',on:'On',off:'Off',installTitle:'Play offline',installText:'On iPhone, open this page in Safari. Tap Share, then Add to Home Screen. Open the game once online before playing offline.',
    ruleGoal:'Keep your total low. Each heart is 1 point; the queen of spades is 13. When someone reaches 100, the lowest total wins. A tie for lowest continues for another hand.',
    rulePass:'Choose three cards, then confirm the pass. Passing goes left, right, across, then no passing. Review the cards you receive before continuing.',
    rulePlay:'The 2 of clubs starts each hand. Follow the suit that was led if you can. Otherwise, play any legal card. On the first trick, you must avoid hearts and the queen of spades if another card is available.',
    ruleHearts:'You can lead hearts after a heart has been played, or when you have only hearts. The queen of spades does not break hearts. The highest card of the led suit takes the trick.',
    ruleMoon:'Take all 13 hearts and the queen of spades to shoot the moon. You add zero points; each other player adds 26.',
    ruleControls:'Tap a card to select it, then press Play card. You can change your choice before confirming. The cards move into the winner’s pile. Press Next trick when you are ready. Menu includes the last trick and settings.'
  };
  const es = {
    title:'Corazones',you:'Tú',menu:'Menú',help:'Cómo jugar',close:'Cerrar',back:'Volver al juego',settings:'Ajustes',newGame:'Nueva partida',restartTitle:'¿Nueva partida?',restartText:'Se reemplazará la partida actual.',keepPlaying:'Seguir jugando',start:'Nueva partida',totalScores:'Puntos totales · gana el menor',handPoints:'Esta mano: tienes {n} puntos.',lastTrick:'Última baza',saveNote:'Tu progreso se guarda automáticamente.',savedProblem:'No se pudo guardar. Mantén abierta esta pestaña.',recovered:'Se recuperó la partida anterior.',damaged:'No se pudo recuperar la partida. Hay una nueva lista.',
    choose3:'Elige 3 cartas',ready:'Listas para pasar',passLeft:'Pasar izquierda',passRight:'Pasar derecha',passAcross:'Pasar enfrente',passTo:'Pasa a {name} · {direction}',left:'izquierda',right:'derecha',across:'enfrente',hold:'Esta mano no se pasan cartas',count3:'{n} de 3',limit3:'Ya elegiste tres. Quita una antes de elegir otra.',received:'Cartas recibidas',receivedFrom:'3 cartas de {name}',newLabel:'NUEVA',continue:'Continuar',begin:'Empezar',yourTurn:'Tu turno',turn:'Turno de {name}',chooseCard:'Elige una carta',chooseSuit:'Elige {suit}',leadTwo:'Juega el 2 de tréboles',follow:'Tu turno · {suit}',playCard:'Jugar carta',choose1:'Elige 1',wait:'Espera',nextTrick:'Siguiente baza',seeScores:'Ver puntos',cardPlayed:'Baza terminada',trickWon:'{name} ganó · {n} puntos',yourTrick:'Ganaste la baza · {n} puntos',chooseLegal:'Elige una carta permitida por las reglas.',selected:'{card}. Pulsa Jugar carta para confirmar.',
    clubs:'tréboles',diamonds:'diamantes',spades:'picas',hearts:'corazones',ace:'As',jack:'Jota',queen:'Reina',king:'Rey',cardName:'{rank} de {suit}',handNumber:'Mano {n}',points:'{n} puntos',player:'Jugador',thisHand:'Esta mano',total:'Total',handComplete:'Mano terminada',lowest:'Gana el total más bajo.',youWon:'¡Ganaste!',won:'Ganó {name}',lowestScore:'{n} puntos · el menor total',moon:'{name} hizo pleno',moonDetail:'Un jugador tomó todos los corazones y la reina de picas. Los demás suman 26 puntos.',endReason:'Alguien llegó a 100 puntos. Gana el total más bajo.',tie:'Empate en el menor total. Juega otra mano.',nextPass:'Próxima mano: pasar {direction}.',nextHold:'Próxima mano: conserva tus cartas.',playAgain:'Jugar de nuevo',reviewTrick:'Ver última baza',tookTrick:'{name} ganó esta baza.',youTookTrick:'Ganaste esta baza.',led:'{name} salió con {suit}.',noPoints:'Sin corazones ni reina de picas.',queenPoints:'Reina de picas: 13',heartPoints:'Corazones: {n}',
    language:'Idioma',pace:'Velocidad de rivales',slow:'Tranquila',normal:'Normal',fast:'Rápida',sound:'Sonidos suaves',on:'Sí',off:'No',installTitle:'Jugar sin conexión',installText:'En iPhone, abre la página en Safari. Pulsa Compartir y Añadir a pantalla de inicio. Abre el juego una vez con conexión antes de jugar sin internet.',ruleGoal:'Mantén bajo tu total. Cada corazón vale 1 punto; la reina de picas, 13. Al llegar alguien a 100, gana el menor total. Si hay empate en el menor total, se juega otra mano.',rulePass:'Elige tres cartas y confirma. Se pasan a la izquierda, a la derecha, enfrente y luego no se pasan. Revisa las cartas recibidas antes de continuar.',rulePlay:'Empieza el 2 de tréboles. Sigue el palo de salida si puedes; si no, juega una carta permitida. En la primera baza, evita corazones y la reina de picas si tienes otra carta.',ruleHearts:'Puedes salir con corazones después de que se haya jugado uno, o si solo tienes corazones. La reina de picas no los habilita. Gana la carta más alta del palo de salida.',ruleMoon:'Tomar todos los corazones y la reina de picas es hacer pleno: tú sumas cero y los demás suman 26.',ruleControls:'Toca una carta y confirma con Jugar carta. Puedes cambiarla antes de confirmar. Las cartas van al montón de quien ganó. Pulsa Siguiente baza cuando estés lista. El Menú incluye la última baza y los ajustes.'
  };
  const vi = {
    title:'Hearts',you:'Bạn',menu:'Menu',help:'Cách chơi',close:'Đóng',back:'Trở lại bàn',settings:'Cài đặt',newGame:'Ván mới',restartTitle:'Bắt đầu ván mới?',restartText:'Ván hiện tại sẽ được thay thế.',keepPlaying:'Chơi tiếp',start:'Bắt đầu ván mới',totalScores:'Tổng điểm · ít nhất thắng',handPoints:'Lượt này: bạn có {n} điểm.',lastTrick:'Lượt đánh trước',saveNote:'Tiến trình được lưu tự động.',savedProblem:'Không lưu được. Hãy giữ thẻ này mở.',recovered:'Đã khôi phục bản lưu trước.',damaged:'Không khôi phục được ván đã lưu. Đã chia ván mới.',
    choose3:'Chọn 3 lá',ready:'Sẵn sàng chuyển',passLeft:'Chuyển trái',passRight:'Chuyển phải',passAcross:'Chuyển đối diện',passTo:'Chuyển cho {name} · {direction}',left:'trái',right:'phải',across:'đối diện',hold:'Lượt này không chuyển bài',count3:'{n} trên 3',limit3:'Đã chọn ba lá. Bỏ chọn một lá trước khi chọn lá khác.',received:'Bài vừa nhận',receivedFrom:'Nhận 3 lá từ {name}',newLabel:'MỚI',continue:'Tiếp tục',begin:'Bắt đầu chơi',yourTurn:'Đến lượt bạn',turn:'Lượt của {name}',chooseCard:'Chọn một lá',chooseSuit:'Chọn lá {suit}',leadTwo:'Đánh lá 2 tép',follow:'Lượt bạn · theo {suit}',playCard:'Đánh bài',choose1:'Chọn 1 lá',wait:'Vui lòng chờ',nextTrick:'Lượt tiếp',seeScores:'Xem điểm',cardPlayed:'Xong lượt đánh',trickWon:'{name} ăn bài · {n} điểm',yourTrick:'Bạn ăn bài · {n} điểm',chooseLegal:'Chọn một lá được phép đánh.',selected:'Đã chọn {card}. Nhấn Đánh bài để xác nhận.',
    clubs:'tép',diamonds:'rô',spades:'bích',hearts:'cơ',ace:'Át',jack:'J',queen:'Q',king:'K',cardName:'{rank} {suit}',handNumber:'Lượt chia {n}',points:'{n} điểm',player:'Người chơi',thisHand:'Lượt này',total:'Tổng',handComplete:'Xong lượt chia',lowest:'Tổng điểm ít nhất thắng.',youWon:'Bạn thắng!',won:'{name} thắng',lowestScore:'{n} điểm · tổng thấp nhất',moon:'{name} ăn trọn điểm',moonDetail:'Một người ăn đủ 13 lá cơ và Q bích. Mỗi người còn lại cộng 26 điểm.',endReason:'Có người đạt 100 điểm. Tổng điểm thấp nhất thắng.',tie:'Đồng hạng thấp nhất. Chơi thêm một lượt chia.',nextPass:'Lượt sau: chuyển {direction}.',nextHold:'Lượt sau: giữ nguyên bài.',playAgain:'Chơi lại',reviewTrick:'Xem lượt đánh trước',tookTrick:'{name} ăn lượt bài này.',youTookTrick:'Bạn ăn lượt bài này.',led:'{name} đi {suit} trước.',noPoints:'Không có lá cơ hay Q bích.',queenPoints:'Q bích: 13',heartPoints:'Lá cơ: {n}',
    language:'Ngôn ngữ',pace:'Tốc độ đối thủ',slow:'Chậm',normal:'Vừa',fast:'Nhanh',sound:'Âm thanh nhẹ',on:'Bật',off:'Tắt',installTitle:'Chơi ngoại tuyến',installText:'Trên iPhone, mở trang bằng Safari. Nhấn Chia sẻ rồi Thêm vào Màn hình chính. Mở trò chơi một lần khi có mạng trước khi chơi ngoại tuyến.',ruleGoal:'Giữ tổng điểm thấp. Mỗi lá cơ là 1 điểm; Q bích là 13. Khi có người đạt 100 điểm, tổng thấp nhất thắng. Nếu đồng hạng thấp nhất, chơi thêm một lượt chia.',rulePass:'Chọn ba lá rồi xác nhận. Chuyển trái, phải, đối diện, rồi không chuyển. Xem các lá vừa nhận trước khi tiếp tục.',rulePlay:'Lá 2 tép mở đầu. Phải theo chất được đánh trước nếu có. Nếu không, đánh lá hợp lệ khác. Trong lượt đánh đầu, tránh cơ và Q bích nếu còn lá khác.',ruleHearts:'Chỉ được đi cơ trước sau khi đã có lá cơ được đánh, hoặc khi chỉ còn cơ. Q bích không mở cơ. Lá cao nhất của chất đi trước ăn bài.',ruleMoon:'Ăn đủ 13 lá cơ và Q bích thì bạn cộng 0 điểm, mỗi người còn lại cộng 26.',ruleControls:'Chạm một lá rồi nhấn Đánh bài. Có thể đổi lựa chọn trước khi xác nhận. Các lá bài chuyển về chồng bài của người thắng. Nhấn Lượt tiếp khi đã sẵn sàng. Menu có lượt đánh trước và cài đặt.'
  };
  const languages = {en,es,vi};
  let language = 'en';
  function set(value) { language = Object.hasOwn(languages,value) ? value : 'en'; document.documentElement.lang = language; }
  function t(key, values = {}) { return (languages[language][key] || en[key] || key).replace(/\{(\w+)\}/g,(_,name)=>String(values[name] ?? '')); }
  return {set,t,keys:Object.keys(en),languages};
})();
